backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: gaver
    label: Gaver
    folder: "src/gifts"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Tittel", name: "title" , widget: "string"}
      - {label: "Hvem", name: "hvem" , widget: "string"}
      - {label: "Beskrivelse", name: "desc" , widget: "string", required: false}
      - {label: "Bilde", name: "img" , widget: "image", required: false}
      - {label: "Bildetekst", name: "imgAlt" , widget: "string", required: false}
      - {label: "URL", name: "externalUrl", widget: "string", required: false}
      - {label: "Tags", name: "tags" , widget: "list", default: ["gave"]}
